---
id: https://w3id.org/turbomam/reactions_for_owl/project
name: reactions-for-owl-project
title: reactions for owl project
description: |-
  Project module for a OWL-friendly model of proteolytic reactions
license: MIT
see_also:
  - https://turbomam.github.io/reactions-for-owl

prefixes:
  reactions_for_owl: https://w3id.org/turbomam/reactions-for-owl/
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
  schema: http://schema.org/
  PATO: http://purl.obolibrary.org/obo/PATO_
  example: https://example.org/
default_prefix: reactions_for_owl
default_range: string

imports:
  - linkml:types
  - core

classes:


